#!/bin/sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"
export PYTHONPATH="$ROOT_DIR${PYTHONPATH:+:$PYTHONPATH}"

ensure_bootstrap() {
  if [ ! -f alembic.ini ]; then
    cat > alembic.ini <<'EOF'
# Auto-generated by scripts/migrate.sh
[alembic]
script_location = migrations
sqlalchemy.url = postgresql+asyncpg://spooky:spooky@db:5432/spookydb

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %Y-%m-%d %H:%M:%S
EOF
  fi

  if [ ! -d migrations ]; then
    mkdir -p migrations
  fi

  if [ ! -f migrations/env.py ]; then
    mkdir -p migrations/versions
    cat > migrations/env.py <<'EOF'
"""
Alembic environment configuration for Spooky.

This file is created automatically by scripts/migrate.sh when the project has
not been initialised yet. It configures Alembic to:

- Resolve the database URL from environment variables (the same ones the bot
  uses: ``DATABASE_URL`` or the granular ``DB_*`` values).
- Use SQLAlchemy's async engine so migrations work with the ``asyncpg`` driver.
- Expose the project's declarative metadata for autogeneration.
"""

from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig
from typing import Any
from urllib.parse import quote_plus

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import AsyncEngine, async_engine_from_config

from spooky.models.base_models.base import Base


config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _build_database_url() -> str:
    url = os.getenv("DATABASE_URL")
    if url:
        return url

    driver = os.getenv("DB_DRIVER", "postgresql+asyncpg")
    user = quote_plus(os.getenv("DB_USER", "spooky"))
    password = quote_plus(os.getenv("DB_PASS", "spooky"))
    host = os.getenv("DB_HOST", "db")
    port = os.getenv("DB_PORT", "5432")
    name = os.getenv("DB_NAME", "spookydb")
    return f"{driver}://{user}:{password}@{host}:{port}/{name}"


def _configure_context(**kwargs: Any) -> None:
    context.configure(
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
        **kwargs,
    )


def run_migrations_offline() -> None:
    url = _build_database_url()
    config.set_main_option("sqlalchemy.url", url)

    _configure_context(url=url, literal_binds=True, dialect_opts={"paramstyle": "named"})

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    config_section = config.get_section(config.config_ini_section, {})
    config_section = dict(config_section or {})
    config_section["sqlalchemy.url"] = _build_database_url()

    connectable: AsyncEngine = async_engine_from_config(
        config_section,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    def do_run_migrations(connection) -> None:
        _configure_context(connection=connection)
        with context.begin_transaction():
            context.run_migrations()

    async def _run() -> None:
        async with connectable.connect() as connection:
            await connection.run_sync(do_run_migrations)
        await connectable.dispose()

    asyncio.run(_run())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
EOF
  elif [ ! -d migrations/versions ]; then
    mkdir -p migrations/versions
  fi

  if [ ! -f migrations/script.py.mako ]; then
    cat > migrations/script.py.mako <<'EOF'
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}


# revision identifiers, used by Alembic.
revision = '${up_revision}'
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade():
    ${upgrades if upgrades else "pass"}


def downgrade():
    ${downgrades if downgrades else "pass"}
EOF
  fi
}

ensure_bootstrap

has_revision_files() {
  find migrations/versions -type f -name "*.py" -print -quit | grep -q .
}

autogenerate_initial_revision() {
  if has_revision_files; then
    return
  fi

  message=${INIT_REVISION_MESSAGE:-init}
  echo "No Alembic revisions detected; autogenerating initial revision \"$message\"..."

  if [ "${RESET_MISSING_REVISION:-1}" != "0" ]; then
    echo "Resetting Alembic version table (dropping stale entries)..."
    poetry run python - <<'PY' || true
import asyncio
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from spooky.core import get_database_url


async def reset() -> None:
    engine = create_async_engine(get_database_url(), isolation_level="AUTOCOMMIT")
    async with engine.begin() as conn:
        await conn.execute(text("DROP TABLE IF EXISTS alembic_version"))
    await engine.dispose()


asyncio.run(reset())
PY
  fi

  poetry run alembic revision --autogenerate -m "$message"
}

cmd="${1:-upgrade}"
if [ $# -gt 0 ]; then
  shift
fi

case "$cmd" in
  revision)
    message="${1:-auto}"
    if [ $# -gt 0 ]; then
      shift
    fi
    poetry run alembic revision --autogenerate -m "$message" "$@"
    ;;
  upgrade|downgrade)
    target="${1:-head}"
    if [ $# -gt 0 ]; then
      shift
    fi
    if [ "$cmd" = "upgrade" ] && [ "$target" = "head" ] && [ "${AUTO_GENERATE_REVISION:-1}" != "0" ]; then
      autogenerate_initial_revision
    fi
    poetry run alembic "$cmd" "$target" "$@"
    ;;
  *)
    poetry run alembic "$cmd" "$@"
    ;;
esac
